// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wupedrveftofxcdrmfwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1cGVkcnZlZnRvZnhjZHJtZndvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwOTIwOTgsImV4cCI6MjA2NzY2ODA5OH0.lqejyXUO0mGU-szFNwkBrtXqnBAIICIhnTYxQhoWYeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);